### ISSUE TITLE
登录遇到的问题

### ISSUE THREAD

**Issue by kukudemajia** [jwma/jump-jump#1]
创建管理用户
./app -username=YourUsername -password=YourPassword
在redis里面只查询到一个key就比如"u'YourUsername"
打开登陆页面，输入用户名和密码，点登陆没有任何提示。
![QQ截图20200220220359](https://user-images.githubusercontent.com/17118600/74940816-f8f01800-542c-11ea-881a-1a1eff21155d.jpg)

因为跟现有端口冲突，所以改了一下端口
docker-compose-dev.yml：
version: "3"

volumes:
  node_modules:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    depends_on:
      - redis
    container_name: jump-jump-dev
    ports:
      - "9999:8081"
    environment:
      J2HttpPort: 8081
      J2RunMode: dev
      J2RedisAddr: redis:6379
    volumes:
      - "$PWD:/go/src/github.com/jwma/jump-jump"
    entrypoint: bee run

  frontend:
    build:
      context: ./admin-app
    container_name: jump-jump-admin-app-dev
    volumes:
      - "$PWD/admin-app:/home/node/app"
      - "node_modules:/home/node/app/node_modules"
    ports:
      - "9090:8080"
    working_dir: /home/node/app
    entrypoint: npm run serve

  redis:
    image: redis:latest
    volumes:
      - "$PWD/data/dev/redis:/data"
    ports:
      - "6380:6379"
    entrypoint: redis-server --appendonly yes

感谢分享。

**Comment by jwma** [comment]
你好，谢谢你对这个项目感兴趣，我明天抽空看下哈

**Comment by jwma** [comment]
@kukudemajia 
1. 将 admin-app 目录下的 .env.default 文件拷贝一份到相同目录，并命名为 .env.local
2. 如果已经启动了服务，需要重启服务

**Comment by kukudemajia** [comment]
> @kukudemajia
> 
> 1. 将 admin-app 目录下的 .env.default 文件拷贝一份到相同目录，并命名为 .env.local
> 2. 如果已经启动了服务，需要重启服务

非常感谢，已经解决。
