### ISSUE TITLE
Breaking changes，访问记录存储优化

### ISSUE THREAD

**Issue by jwma** [jwma/jump-jump#19]
## 背景

在前期设计时，没有过多考虑到数据统计、报表的需求，所以在存储访问请求的数据类型上选择不恰当，原计划在 v1.3.0 版本中增加关于短链接的数据统计相关特性，但在准备开发时发现 `list` 的确不利于数据统计，所以会在 v1.3.0 版本中先修改其为 `zset`。（当然，我到目前为止还是没有想要加入传统数据库到 jump-jump 来）

## 改动

- #17
- #18

## 升级至 v1.3.0

如果你原本已经部署过 v1.3.0 之前的版本，现在需要升级到 v1.3.0 版本且希望保留过往的短链接访问记录数据，则需要在部署 v1.3.0 之后，运行 `migraterequesthistory` 程序，假设你是使用 docker-compose 部署，则可以这样操作：
```
docker-compose -f deployments/docker-compose.yaml exec apiserver ./migraterequesthistory
```

在看到类似于这样的输出后，则代表数据迁移完毕：
```
[V1.2.0] 总共有 2 个短链接的访问记录可能需要迁移
[V1.2.0] 迁移完毕

[V1.3.0] 总共有 2 个短链接的访问记录可能需要迁移
[V1.3.0] 迁移完毕
```

**Comment by guvmao** [comment]
![image](https://user-images.githubusercontent.com/40655731/87396023-dbdb0200-c5e4-11ea-859d-90b46dab3949.png)
已升级，非常美妙~
