### ISSUE TITLE
长链接有特殊符号，前端校验不通过

### ISSUE THREAD

**Issue by it-wwh** [jwma/jump-jump#23]
您好，请问针对这个问题可以修复一下吗
![image](https://user-images.githubusercontent.com/35522446/86443453-ddcdd700-bd41-11ea-9839-5417d7579136.png)

**Comment by jwma** [comment]
好的，这个 bug 已经记录在我的小本本上了，我会尽快抽时间兼容一下 SPA 常用的 URL。

**Comment by jwma** [comment]
@it-wwh 这个问题我修复好了，你可以在体验网址测试一下。

**Comment by it-wwh** [comment]
已经修复好了，非常感谢🙏

**Comment by Goddywu** [comment]
https://www.cctalk.com/m/group/83195283?xh_fshareuid=65938734&ch_source=10013473&utr=10013437,11347,757903,14343

@it-wwh   您好， 我的地址也校验不通过～，测试了下是逗号引起的。

**Comment by jwma** [comment]
> https://www.cctalk.com/m/group/83195283?xh_fshareuid=65938734&ch_source=10013473&utr=10013437,11347,757903,14343
> 
> @it-wwh 您好， 我的地址也校验不通过～，测试了下是逗号引起的。

@Goddywu 我是作者哦，有问题的话可以 @ 我。

这种情况属于 Query string 包含特殊符号没能通过验证，当时的确没有仔细思考关于这个长链接特殊符号的问题，我会尽快深度的修复下这个问题。请持续关注更新。

谢谢你反馈这个问题。

**Comment by jwma** [comment]
@Goddywu 这个问题修复好了，具体修复方案可以查看 #33 。

如果觉得这个项目不错，可以给个star哦~哈哈哈
