### ISSUE TITLE
目标链接折叠显示

### ISSUE THREAD

**Issue by guvmao** [jwma/jump-jump#26]
长链接过长时，Dashboard 比较影响观感，希望目标链接可以折叠显示

**Comment by jwma** [comment]
好建议👍，排在 1.4.0 搞吧，这两天会先把 1.3.0 报表相关的做好。

**Comment by jwma** [comment]
@guvmao 这个优化更新了，可以查看 [v1.4.0-beta.1](https://github.com/jwma/jump-jump/releases/tag/v1.4.0-beta.1)。

给目标链接的容器设置了一个固定宽度，过长的话就显示 **...**，鼠标放在目标链接上面，会出现一个跟短链接一样的下拉框，里面展示了完整的目标链接，点击会拷贝长链接。

谢谢你的优化建议！😁
