### ISSUE TITLE
版本规划

### ISSUE THREAD

**Issue by jwma** [jwma/jump-jump#3]
![v1 features](http://rs.majiawei.com/jumpjump/v1features.jpg16061585209737_.pic_hd.jpg)

**Comment by catwithtudou** [comment]
请问博主这个版本规划的整理是用的什么软件呀

**Comment by jwma** [comment]
@catwithtudou 
软件是 teambition，web、手机 App 都有。
你想快速体验的话，访问 j2.anmuji.com，账号密码都是 guest。

谢谢你对这个项目的关注哦~
