### ISSUE TITLE
通过API获取(创建短链)

### ISSUE THREAD

**Issue by ShadowWaIker** [jwma/jump-jump#39]
有这个功能吗？翻了文档和Issue好像没看到有提到过这方面的内容。

**Comment by jwma** [comment]
因为采用了前后端分离的方式（采用 token 的鉴权，非 session），所有这个项目的所有接口都是可以直接调用的，你可以查看源码目录的 `/api` 目录，这里面就有接口调用的代码（IDEA http client 格式），虽然不一定符合大家的调用方式，但我猜你看一下就能明白怎么调用了。

目前里面的调用代码还没有同步到最新，今天内我应该会更新一下。

**Comment by jwma** [comment]
@ShadowWaIker 
如果你很着急，其实你可以把项目部署好，然后访问管理后台，在创建短链接的时候打开浏览器的调试功能，然后创建短链接，再到请求列表里面看看接口请求的时候的参数，其实就能够自己把接口调用给扒出来了。

**Comment by ShadowWaIker** [comment]
看了下源码，我感觉好像是 fork 一个 [CreateShortLinkAPI](https://github.com/jwma/jump-jump/blob/13d707ce99a398addfcf8b02af84c1c60f458071/internal/app/handlers/shortlink.go#L48) 函数，然后把 JWT 验证改成对接第三方系统的验证方式就行？
或者，我是不是还可以在不修改这个接口的前提下，通过签发一个长期有效的 JWT Token 来用来对接第三方的系统？大概瞄了一眼登陆部分的源码，签发的 Token 是 2 小时过期的。我没用过 JWT ，不太确定增加有效期这个方案是否可行  XD

**Comment by jwma** [comment]
> 看了下源码，我感觉好像是 fork 一个 [CreateShortLinkAPI](https://github.com/jwma/jump-jump/blob/13d707ce99a398addfcf8b02af84c1c60f458071/internal/app/handlers/shortlink.go#L48) 函数，然后把 JWT 验证改成对接第三方系统的验证方式就行？
> 或者，我是不是还可以在不修改这个接口的前提下，通过签发一个长期有效的 JWT Token 来用来对接第三方的系统？大概瞄了一眼登陆部分的源码，签发的 Token 是 2 小时过期的。我没用过 JWT ，不太确定增加有效期这个方案是否可行 XD

如果你是希望在其他系统使用这个功能，其实是可行的，最重要的就是 token 要保存好。

你可以修改 `internal/app/utils/auth.go`，直接修改 JWT 生成时候设置的过期时间，或者你有更细致的需求，那就再按需修改一下。

**Comment by ShadowWaIker** [comment]
了解，感谢～
