### ISSUE TITLE
apiserver后台提示：你的登入已过期，请重新登入

### ISSUE THREAD

**Issue by jxzzlfh** [jwma/jump-jump#45]
在服务器上部署jump-jump完成，成功登录后台，过一段时间总是提示：你的登入已过期，请重新登入，这个问题怎么解决？

**Comment by jwma** [comment]
@jxzzlfh 你好，因为登录态的有效时间目前定死了是两个小时，也就是说每两个小时需要重新登入一次。

我会在新版加一个可配置的形式来动态调整这个登录态的有效时间，如果你比较着急的话，可以修改 https://github.com/jwma/jump-jump/blob/bf480797793b70bf7e671901033aece878048730/internal/app/utils/auth.go#L29 。
