### ISSUE TITLE
workflow 中的 deploy 脚本可以给个例子吗

### ISSUE THREAD

**Issue by GiaoGiaoCat** [jwma/jump-jump#46]
在 build_and_deploy.yml 的最后一步，执行了服务器上 ./deploy/deploy-jump-jump.sh 的脚本用来部署 docker。
可以给个例子吗，谢谢。

**Comment by jwma** [comment]
那个脚本其实就是从远程的镜像仓库拉取最新的 jump-jump 镜像，然后用 `docker-compose up -d` 来使用最新镜像重启服务。

给个简单的示例：

```shell
#!/bin/sh

set -e

docker pull 远程镜像仓库地址/jump-jump:latest # 例如：docker pull studiomj/jump-jump:latest

cd /path/to/docker-compose.yaml所在目录

docker-compose up -d
```
