### ISSUE TITLE
如何找回密码？

### ISSUE THREAD

**Issue by guvmao** [jwma/jump-jump#47]

**Comment by jwma** [comment]
目前只能去 redis 删掉对应的用户，然后再创建一个和之前一样用户名的用户。有点忙所以开源的项目顾不过来，后续可以加一个重置密码的命令，因为要做常规的重置/找回密码的功能，免不了做发送邮件/短信等，感觉如果要集成这些需求的话，不适合目前的 jump jump，这个项目更多的是自己部署自己用。
