### ISSUE TITLE
执行make dockerimage 报错

### ISSUE THREAD

**Issue by linuxxx** [jwma/jump-jump#49]
verifying github.com/google/gofuzz@v1.0.0: github.com/google/gofuzz@v1.0.0: Get https://sum.golang.org/lookup/github.com/google/gofuzz@v1.0.0: dial tcp 172.217.163.49:443: i/o timeout

**Comment by jwma** [comment]
应该是你运行这个命令所在的机器网络的问题，我这边可以正常运行哦。
