### ISSUE TITLE
部署完成访问后台400

### ISSUE THREAD

**Issue by RoyceShaw** [jwma/jump-jump#52]
请问一下这个是什么原因？
<img width="527" alt="image" src="https://user-images.githubusercontent.com/48939516/195343780-ef0393a3-cacd-484a-a150-46d76b047f95.png">

**Comment by zhoupengcheng** [comment]
估计是go里面有些没有配置好，我后面改了改源码，先本地跑起来了才重新打包，部署

**Comment by jwma** [comment]
我估计大概率是因为没有设置：`ALLOWED_HOSTS`，详见如下文章的 docker-compose.yaml 部分
https://sourl.xyz/7yw1ka

**Comment by jwma** [comment]
很抱歉现在才回复，之前看到，突然又忙工作去了，所以...
望体谅。
