### ISSUE TITLE
管理后台打开是空白页

### ISSUE THREAD

**Issue by kukudemajia** [jwma/jump-jump#7]
apiserver有访问日志出现
已经修改了默认端口
之前的版本可以正常运行

**Comment by jwma** [comment]
你是按照最新 master 的启动方式启动的吗？

**Comment by jwma** [comment]
@kukudemajia 
这个问题跟我昨天更新的 #4 有关，但我仔细看了下，发现有个小问题，**谢谢你的反馈！** 我现在已经修正了这个问题，见 PR #8 

另外我建议，如果你需要部署到自己的服务器使用，可以 使用已经 [release](https://github.com/jwma/jump-jump/releases) 的版本哦。

**Comment by kukudemajia** [comment]
> @kukudemajia
> 这个问题跟我昨天更新的 #4 有关，但我仔细看了下，发现有个小问题，**谢谢你的反馈！** 我现在已经修正了这个问题，见 PR #8
> 
> 另外我建议，如果你需要部署到自己的服务器使用，可以使用已经 [release](https://github.com/jwma/jump-jump/releases) 的版本哦。

好的，非常感谢
