### ISSUE TITLE
优化：指定短链接随机 ID 长度

### ISSUE THREAD

**Issue by kukudemajia** [jwma/jump-jump#9]
jump-jump-v1.1.1
建议保留原有自动随机生成的功能，并可以指定随机生成的短链接的长度
同时保留现有的指定ID的功能，这样会更灵活方便
因为有些特殊的需要指定方便记忆，其它或许随机生成即可

**Comment by jwma** [comment]
@kukudemajia 
指定 ID 不是必填的，你不填的话就是随机 ID，另外指定 ID 只有管理员角色才有哦。
我可能得在添加面板加点说明吧，我想刚使用 jump jump 的人可能也会存在跟你一样的疑惑。

你建议的指定随机生成 ID 的长度，意思是做成一个全局的配置？还是说每个短链接在添加的时候都可以指定长度？

**Comment by kukudemajia** [comment]
> @kukudemajia
> 指定 ID 不是必填的，你不填的话就是随机 ID，另外指定 ID 只有管理员角色才有哦。
> 我可能得在添加面板加点说明吧，我想刚使用 jump jump 的人可能也会存在跟你一样的疑惑。
> 
> 你建议的指定随机生成 ID 的长度，意思是做成一个全局的配置？还是说每个短链接在添加的时候都可以指定长度？

原来如此，还是在后面添加说明比较合适
个人觉得做成全局配置比较好，特殊的可以指定，很灵活

**Comment by jwma** [comment]
@kukudemajia 嗯，我刚也想了一下，在全局加个默认的长度配置，然后优化一下添加面板，我先把这个优化需求加入到 v1.2.0  吧，到时候发布了，你就能用上了~哈哈

**Comment by jwma** [comment]
@kukudemajia 我现在会修改一下这个 issue 的标题，别介意哈

**Comment by jwma** [comment]
这个 issue 先保持 open 吧，等我做完了我再 close 掉
